---
sudo: required
language: python
python:
  - "3.6"
services:
  - docker

env:
  global:
    - ANSIBLE_HOST_KEY_CHECKING="False"

# Install python-pip
addons:
  apt:
    packages:
      - python-pip


before_install:
  - docker pull centos:7

install:
  - pip install tox ansible yamllint

  # Check ansible version
  - ansible --version

script:
  # Run sytax checks and linters
  - tox
  - cd kubevirt-provider/ && docker build -t v2v-conversion-host .
  - docker run --detach --publish 8080:8080 v2v-conversion-host
  - curl -v http://localhost:8080/healthcheck
  - docker kill $(docker ps --quiet --latest)

# Galaxy cannot handle the fact that role is in subdirectory
# notifications:
#   webhooks: https://galaxy.ansible.com/api/v1/notifications/
