// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OVirtProvider) DeepCopyInto(out *OVirtProvider) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OVirtProvider.
func (in *OVirtProvider) DeepCopy() *OVirtProvider {
	if in == nil {
		return nil
	}
	out := new(OVirtProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OVirtProvider) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OVirtProviderList) DeepCopyInto(out *OVirtProviderList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OVirtProvider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OVirtProviderList.
func (in *OVirtProviderList) DeepCopy() *OVirtProviderList {
	if in == nil {
		return nil
	}
	out := new(OVirtProviderList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OVirtProviderList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OVirtProviderSpec) DeepCopyInto(out *OVirtProviderSpec) {
	*out = *in
	if in.Vms != nil {
		in, out := &in.Vms, &out.Vms
		*out = make([]OVirtVM, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OVirtProviderSpec.
func (in *OVirtProviderSpec) DeepCopy() *OVirtProviderSpec {
	if in == nil {
		return nil
	}
	out := new(OVirtProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OVirtProviderStatus) DeepCopyInto(out *OVirtProviderStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OVirtProviderStatus.
func (in *OVirtProviderStatus) DeepCopy() *OVirtProviderStatus {
	if in == nil {
		return nil
	}
	out := new(OVirtProviderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OVirtVM) DeepCopyInto(out *OVirtVM) {
	*out = *in
	out.Detail = in.Detail
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OVirtVM.
func (in *OVirtVM) DeepCopy() *OVirtVM {
	if in == nil {
		return nil
	}
	out := new(OVirtVM)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OVirtVMDetail) DeepCopyInto(out *OVirtVMDetail) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OVirtVMDetail.
func (in *OVirtVMDetail) DeepCopy() *OVirtVMDetail {
	if in == nil {
		return nil
	}
	out := new(OVirtVMDetail)
	in.DeepCopyInto(out)
	return out
}
